# Utilisez une image de base, par exemple Ubuntu 20.04
FROM ubuntu:20.04

# Installez les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip 

# Exécutez des commandes lors de la création de l'image (optionnel)
# ...

# Définissez le répertoire de travail à l'intérieur du conteneur
WORKDIR /app

# Copiez les fichiers de votre machine locale vers le conteneur
COPY requirement.txt /app/


# Exposez un port (si votre application en a besoin)
EXPOSE 8080

# Commande par défaut pour lancer votre application
CMD ["votre_commande_de_demarrage"]
