version: '3'

services:
  serveur_container:
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  serveur_api:
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
